---
title: "Taller2"
author: "Beltran Henry, Burbano Joel, Guaman Ronny"
date: "15/6/2021"
output: html_document
---
```{r include=FALSE}
# install.packages()
```

Considerando el generador congruencial multiplicativo de parámetros $a=7^5=16807$, $c=0$ y $m=2^{31}-1$

**a)**¿Se observan los mismo problemas que con el algoritmo RANDU al considerar las tripletas$(x_k, x_{k+1}, x_{k+2})$?


```{r include=TRUE}
initRANDC <- function(semilla=as.numeric(Sys.time()), a=2^16+3, c=0, m=2^31) {
  .semilla <<- as.double(semilla) %% m  #C?lculos en doble precisi?n
  .a <<- a
  .c <<- c
  .m <<- m
  return(invisible(list(semilla=.semilla,a=.a,c=.c,m=.m))) #print(initRANDC())
}

RANDC <- function() {
    if (!exists(".semilla", envir=globalenv())) initRANDC()
    .semilla <<- (.a * .semilla + .c) %% .m
    return(.semilla/.m)
}

RANDCN <- function(n=1000) {
    x <- numeric(n)
    for(i in 1:n) x[i]<-RANDC()
    return(x)
    # return(replicate(n,RANDC()))  # Alternativa m?s r?pida    
}

```

```{r include=TRUE}
initRANDC(2706,7^5,0,2^31-1)
w=RANDCN(9999)
```



