---
title: "Practica 4"
author: "Beltran Henry, Burbano Joel,Guaman Ronny"
date: "6/7/2021"
output: html_document
---

# Taller simulación de distribuciones multidimensionales

*** 1. (Ejercicio 1-Ricardo Cao) La diferencia en precio $(X)$ y entiempo de vida $(Y)$ de un monitor de 17 pulgadas, expresados en tanto po uno con respecto a la media de mercado, puede suponerse una variable aleatoria, $(X,Y)$, con función de densidad dada por***

$$f(x,y)=\left\{\begin{array}{l c} \frac{3}{16}[2-(x^2+y^2)] & \text{ si }\quad x\in[-1,1]\text{ e } y\in[-1,1] \\ \\ 0 & \text{en otro caso} \end{array} \right.$$

*** Simular dicha distribución bidimensional mediante el método de aceptación-rechazo utilizando como densidad auxiliar una de muy sencilla simulación. ¿ Cuál es la eficiencia del algoritmo? Dar, muy brevemente, la idea en que consiste alguno de ellos.***














*** 2. (Ejercicio 7.1 Blog) Considerando la variable aleatoria bidimensional del Ejemplo 7.2 y teniendo en cuenta que la densidad marginal de la variable $X$ es:***

$$f_{X}(x)=\left\{\begin{array}{l c} \frac{1}{8}[5-3x^2] & \text{ si }\quad x\in[-1,1] \\ 0 & \text{en otro caso} \end{array} \right.$$
*** Describir brevemente un algoritmo para la simulación del vector aleatorio basado en el método de las distribuciones condicionadas (asumir que se dispone de un algoritmo para generar observaciones de las distribuciones unidimensionales de interés). ***


Consideramos entonces la función de densidad dada en el ejemplo 7.2 que justamenete es la que se define en el ejercicio anterior.


$$